spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  h2:
    console:
      enabled: true

  jpa:
    hibernate:
      ddl-auto: create

jwt:
  secret-key: ${JWT_SECRET}   # 환경변수 설정 필요
  expiration:
    access-token: 86400000   # 24h (ms)
  issuer: musicjournal