spring:
  datasource:
    url: ${DB_URL}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

jwt:
  secret-key: ${JWT_SECRET}   # 환경변수 설정 필요
  expiration:
    access-token: 3600000     # 1hour (ms)
    refresh-token: 604800000  # 7days (ms)
  issuer: musicjournal

spotify:
  client-id: ${SPOTIFY_CLIENT_ID}
  client-secret: ${SPOTIFY_CLIENT_SECRET}
  token-url: https://accounts.spotify.com/api/token
  api-base-url: https://api.spotify.com/v1
